from base import *
from effects import *

WONDERS = {
    Wonder(
        'rhodos(A)',
        Resources(ore=1),
        3,
        (
            WonderStage(
                Resources(wood=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(clay=3),
                shields_effect(2),
                no_effect
            ),
            WonderStage(
                Resources(ore=4),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'alexandria(A)',
        Resources(glass=1),
        3,
        (
            WonderStage(
                Resources(stone=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(ore=2),
                untradable_resources_effect(
                    Resources(clay=1),
                    Resources(ore=1),
                    Resources(wood=1),
                    Resources(stone=1)
                ),
                no_effect
            ),
            WonderStage(
                Resources(glass=2),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'ephesos(A)',
        Resources(papyrus=1),
        3,
        (
            WonderStage(
                Resources(stone=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(wood=2),
                coins_effect(9),
                no_effect
            ),
            WonderStage(
                Resources(papyrus=2),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'babylon(A)',
        Resources(clay=1),
        3,
        (
            WonderStage(
                Resources(clay=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(wood=3),
                no_effect,
                scientists_guild_effect
            ),
            WonderStage(
                Resources(clay=4),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'olympia(A)',
        Resources(wood=1),
        3,
        (
            WonderStage(
                Resources(wood=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(stone=2),
                free_card_per_age_effect,
                no_effect
            ),
            WonderStage(
                Resources(ore=2),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'halikarnassos(A)',
        Resources(textiles=1),
        3,
        (
            WonderStage(
                Resources(clay=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(ore=3),
                free_card_from_discard_effect,
                no_effect
            ),
            WonderStage(
                Resources(textiles=2),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'gizah(A)',
        Resources(stone=1),
        3,
        (
            WonderStage(
                Resources(stone=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(wood=3),
                no_effect,
                points_effect(5)
            ),
            WonderStage(
                Resources(stone=4),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'rhodos(B)',
        Resources(ore=1),
        2,
        (
            WonderStage(
                Resources(stone=3),
                combine_effects(
                    coins_effect(3),
                    shields_effect(1)
                ),
                points_effect(3)
            ),
            WonderStage(
                Resources(ore=4),
                combine_effects(
                    coins_effect(4),
                    shields_effect(1)
                ),
                points_effect(4)
            )
        )
    ),
    Wonder(
        'alexandria(B)',
        Resources(glass=1),
        3,
        (
            WonderStage(
                Resources(clay=2),
                untradable_resources_effect(
                    Resources(clay=1),
                    Resources(ore=1),
                    Resources(wood=1),
                    Resources(stone=1)
                ),
                no_effect
            ),
            WonderStage(
                Resources(wood=2),
                untradable_resources_effect(
                    Resources(glass=1),
                    Resources(textiles=1),
                    Resources(papyrus=1)
                ),
                no_effect
            ),
            WonderStage(
                Resources(stone=3),
                no_effect,
                points_effect(7)
            )
        )
    ),
    Wonder(
        'ephesos(B)',
        Resources(papyrus=1),
        3,
        (
            WonderStage(
                Resources(stone=2),
                coins_effect(4),
                points_effect(2)
            ),
            WonderStage(
                Resources(wood=2),
                coins_effect(4),
                points_effect(3)
            ),
            WonderStage(
                Resources(papyrus=1, textiles=1, glass=1),
                coins_effect(4),
                points_effect(5)
            )
        )
    ),
    Wonder(
        'babylon(B)',
        Resources(clay=1),
        3,
        (
            WonderStage(
                Resources(clay=1, textiles=1),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(wood=2, glass=1),
                play_last_card_effect,
                no_effect
            ),
            WonderStage(
                Resources(clay=3, papyrus=1),
                no_effect,
                scientists_guild_effect
            )
        )
    ),
    Wonder(
        'olympia(B)',
        Resources(wood=1),
        3,
        (
            WonderStage(
                Resources(wood=2),
                combine_effects(
                    trading_post_effect(0),
                    trading_post_effect(1)
                ),
                no_effect
            ),
            WonderStage(
                Resources(stone=2),
                no_effect,
                points_effect(5)
            ),
            WonderStage(
                Resources(ore=2, textiles=1),
                no_effect,
                copy_guild_effect
            )
        )
    ),
    Wonder(
        'halikarnassos(B)',
        Resources(textiles=1),
        3,
        (
            WonderStage(
                Resources(ore=2),
                free_card_from_discard_effect,
                points_effect(2)
            ),
            WonderStage(
                Resources(clay=3),
                free_card_from_discard_effect,
                points_effect(1)
            ),
            WonderStage(
                Resources(glass=1, papyrus=1, textiles=1),
                free_card_from_discard_effect,
                no_effect
            )
        )
    ),
    Wonder(
        'gizah(B)',
        Resources(stone=1),
        4,
        (
            WonderStage(
                Resources(wood=2),
                no_effect,
                points_effect(3)
            ),
            WonderStage(
                Resources(stone=3),
                no_effect,
                points_effect(5)
            ),
            WonderStage(
                Resources(clay=5),
                no_effect,
                points_effect(5)
            ),
            WonderStage(
                Resources(stone=4, papyrus=1),
                no_effect,
                points_effect(7)
            )
        )
    )
}